"""
Django settings for Qshop project.

Generated by 'django-admin startproject' using Django 2.2.1.

For more information on this file, see
https://docs.djangoproject.com/en/2.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.2/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '*ra&r0b1oltxmhtkn2+^a!4)5m94r!masqpx%l9bhci^+_6ayc'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'Buyer',
    'Seller',
    'Buyer.templatetags',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'Qshop.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'Qshop.wsgi.application'


# Database
# https://docs.djangoproject.com/en/2.2/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
#     }
# }

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'qshop',
        'USER':'root',
        'PASSWORD':'123456',
        'HOST':'localhost',
        'PORT':'3306'
    }
}

# Password validation
# https://docs.djangoproject.com/en/2.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

# TIME_ZONE = 'UTC'
TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True

USE_L10N = True

# USE_TZ = True
USE_TZ = False


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.2/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = (
    os.path.join(BASE_DIR,'static'),
)
# STATIC_ROOT = os.path.join(BASE_DIR,"static")

MEDIA_url = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR,'static')

#
# alipay_public_key_string="""-----BEGIN PUBLIC KEY-----
# MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAwecYb+jwLvuw2nmAHk0zVaQpC/3So4Jv1gZTt06RpBNie2p2PQXiSXdr6zZH7VwAzcTViViXlNZx6SVC2trVxD5saZoX1r9F5wV5SB27TYPDKfbf3kSaxkV/DHgyDCL9WkgzzropVErCNCVPz5dCnpCKjFd7tiiIaSsSDs5K8dLMEzOusdFEJfdwKuNIMQvDtiCxaaeIgHvjLmKh30nbUZby3eDPTGEnV/fLLsnbrHYln7Tg/fiXuCE/8+DPSn8S579N6m338mLHox4GRgdc+xVyfkA21KWPSePoFGOnZLoouBYKDTqS5s5ncxH5Eor+9Q8ZZCp68fIobpkNCR3cdwIDAQAB
# -----END PUBLIC KEY-----"""
# app_private_key_string="""-----BEGIN RSA PRIVATE KEY-----
# MIIEpQIBAAKCAQEAwecYb+jwLvuw2nmAHk0zVaQpC/3So4Jv1gZTt06RpBNie2p2PQXiSXdr6zZH7VwAzcTViViXlNZx6SVC2trVxD5saZoX1r9F5wV5SB27TYPDKfbf3kSaxkV/DHgyDCL9WkgzzropVErCNCVPz5dCnpCKjFd7tiiIaSsSDs5K8dLMEzOusdFEJfdwKuNIMQvDtiCxaaeIgHvjLmKh30nbUZby3eDPTGEnV/fLLsnbrHYln7Tg/fiXuCE/8+DPSn8S579N6m338mLHox4GRgdc+xVyfkA21KWPSePoFGOnZLoouBYKDTqS5s5ncxH5Eor+9Q8ZZCp68fIobpkNCR3cdwIDAQABAoIBAEumfulCh1q9Rd2nI64uzoVuO7l6+RBkFn/5DfZph/bsvTKLccATKJsjJY6qKdvYVlPxpKImV1VxaRXePLwoPtiGxkNZJE3baEle4FebifUPIDiiIeuU9pG+kXfq+RO1HwV3QAc6qF9Dn4s6t221hP9aQ0PH6fNC0x28+RmfsKuxtSVaKI2ZDQPwq39lVguRrQsNXyTxhbdEbnOAK++K6Zx9cFI3XTbsQLoJ3nbkcSY6BDX9W+Ngiy7wKDBsVpZMO+TmdhswS5sfEHVyrhWGitBtb2Zeazp3hEFzE2M8XjCq+otOCOFLPIbD2R6NeVnlim2soCokA7YypmN9jKWi9QkCgYEA8Fmx3vP1vUn4EGo/txbj1fvAKYOMm4aKvOajYE/2F8t7ZqIibTdHXZopbAxy7jMFxl4dkEi9uXFouoIO3UgMBSwxnG2Wr6z6Me0NSfslPmvFAujgjrGS+fJQtdrRmf9Kh/00eCSNjId1RmI3l/pf8PMFKaWbS1sidH/vL94gp9sCgYEAzocu3zuaj97QaayBl1xWwlu1UlIhG0jWB43BccLXUlAPyRIL3NaUkfsiaxncN/fHwOeGvIVoYLWaBeeEcP86MV/b4L+Wd0OMsVbrNGp5q2QCX4GIDLrec/jWQk+uAw2odu0yPuzUahVLdCmWSaweUOglnJN0kKyvKFeC2GZ5npUCgYEA5jPiizp6mawpLf+1uvTvj1oquRhIKgX5B+iXfn3XpP692JVeB+E0N1Cab+SUh9TSqSYnhrRFE0KuHkTHW+XPrXygn8TO2MACeqMjYUJsb5blAV5vBfzKWx9dcnB85NSBXDKGeLP55ykuiBU2Thf+oFcDENqPHOPS4mZOfzhvapUCgYEApVsm9CTMw5QqWfF8cKvF6ydyLc8EIsxWUQX2dBcEPytK+DoytUY4/giMriOuZkFE9fZpslc+EvBTuZZ8O9ydwxp0+aVr22GCLBrjhrwZXlhcbgtP2qFjqob5RW52bItq7o1LRYZpK+aQ2xjQ83uTakP0mUCWe59HPo2SfaDOj2ECgYEAzknjFQqy7UyLJRng7g2vOTaw0J7ZM7gKPkeg1KkC+oo8rCbl7DbRuOwnf3pF4iW/HyA26f9mxqeabKQlI2CeBvU9gHZtDGI+JBnxm/VZYsFGmSnLYp53kJervDYCUGUziXlVCrJIsG2+mLYgUcPiJTSr8JJSASpTXcIKen2Qi3M=
# -----END RSA PRIVATE KEY-----"""
#
# from alipay import Alipay
#
# alipay = Alipay(
#     appid="2016101800717533",
#     app_notify_url=None,
#     app_private_key_string=app_private_key_string,
#     alipay_public_key_string=alipay_public_key_string,
#     sign_type="RSA2",
#     debug=False
# )