# Generated by Django 2.2.1 on 2020-02-27 11:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Seller', '0010_auto_20200227_1929'),
    ]

    operations = [
        migrations.CreateModel(
            name='PayOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_no', models.CharField(max_length=64, unique=True, verbose_name='订单号')),
                ('order_date', models.DateField(auto_now=True, verbose_name='订单创建时间')),
                ('order_status', models.IntegerField(choices=[(1, '未支付'), (2, '已支付'), (3, '待发货'), (4, '已发货'), (5, '拒收'), (6, '已完成')], verbose_name='订单状态')),
                ('order_total', models.FloatField(verbose_name='订单总价')),
                ('order_buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Seller.LoginUser', verbose_name='买家')),
            ],
            options={
                'db_table': 'pay_order',
                'verbose_name_plural': '支付订单',
            },
        ),
        migrations.CreateModel(
            name='OrderGoods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goods_price', models.FloatField(verbose_name='商品单价')),
                ('buy_number', models.IntegerField(verbose_name='购买单品数量')),
                ('buy_count', models.FloatField(verbose_name='购买单品总价')),
                ('goods', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Seller.Goods')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Buyer.PayOrder')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Seller.LoginUser', verbose_name='卖家')),
            ],
            options={
                'db_table': 'order_goods',
                'verbose_name_plural': '订单商品详情',
            },
        ),
    ]
