# Generated by Django 2.2.1 on 2020-02-26 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Seller', '0004_auto_20200225_2011'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoodsType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_label', models.CharField(max_length=32, verbose_name='类型标签')),
                ('type_description', models.TextField(verbose_name='类型描述')),
                ('type_picture', models.ImageField(max_length=64, upload_to='', verbose_name='类型图片')),
            ],
            options={
                'verbose_name_plural': '产品类型',
                'db_table': 'goods_type',
            },
        ),
        migrations.AddField(
            model_name='goods',
            name='goods_picture',
            field=models.ImageField(default='img/1.jpg', upload_to='', verbose_name='商品图片'),
        ),
    ]
