# Generated by Django 2.2.1 on 2020-02-26 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Seller', '0006_auto_20200226_1746'),
    ]

    operations = [
        migrations.AddField(
            model_name='goods',
            name='goods_click',
            field=models.IntegerField(default=0, verbose_name='点击量'),
        ),
        migrations.AddField(
            model_name='goods',
            name='goods_description',
            field=models.TextField(default='good~', max_length=64, verbose_name='商品描述'),
        ),
        migrations.AddField(
            model_name='goods',
            name='goods_tip',
            field=models.TextField(default='见详情页', max_length=32, verbose_name='商品简介'),
        ),
        migrations.AddField(
            model_name='goods',
            name='goods_top',
            field=models.IntegerField(default=1, verbose_name='产品推荐'),
        ),
    ]
