# Generated by Django 2.2.1 on 2020-02-26 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Seller', '0008_auto_20200227_0037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='goods_picture',
            field=models.ImageField(default='img/1.jpg', upload_to='goodsimg', verbose_name='商品图片'),
        ),
        migrations.AlterField(
            model_name='loginuser',
            name='gender',
            field=models.IntegerField(choices=[(0, '女'), (1, '男')], default=1, verbose_name='性别'),
        ),
    ]
