# Generated by Django 2.2.1 on 2020-03-04 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Seller', '0011_auto_20200302_1358'),
    ]

    operations = [
        migrations.CreateModel(
            name='ValidCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=32, verbose_name='用户邮箱')),
                ('code', models.CharField(max_length=8, verbose_name='验证码')),
                ('create_time', models.DateTimeField(auto_now=True, verbose_name='验证码创建时间')),
            ],
            options={
                'db_table': 'validcode',
                'verbose_name_plural': '验证码',
            },
        ),
        migrations.AlterField(
            model_name='goods',
            name='goods_top',
            field=models.IntegerField(choices=[(0, '推荐'), (1, '不推荐')], default=1, verbose_name='产品推荐'),
        ),
        migrations.AlterField(
            model_name='loginuser',
            name='gender',
            field=models.IntegerField(choices=[(0, '女'), (1, '男')], default=1, verbose_name='性别'),
        ),
    ]
