# Generated by Django 2.2.1 on 2020-03-04 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Seller', '0012_auto_20200304_2121'),
    ]

    operations = [
        migrations.RenameField(
            model_name='validcode',
            old_name='user',
            new_name='email',
        ),
        migrations.AlterField(
            model_name='goods',
            name='goods_top',
            field=models.IntegerField(choices=[(1, '不推荐'), (0, '推荐')], default=1, verbose_name='产品推荐'),
        ),
    ]
