# Generated by Django 2.2.1 on 2020-03-04 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Seller', '0013_auto_20200304_2125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loginuser',
            name='gender',
            field=models.IntegerField(choices=[(1, '男'), (0, '女')], default=1, verbose_name='性别'),
        ),
        migrations.AlterField(
            model_name='validcode',
            name='email',
            field=models.EmailField(max_length=32, verbose_name='用户邮箱'),
        ),
    ]
